# INTRODUCCION
 
\ \ \ \ Se sabe que la música ha formado parte de las distintas sociedades a lo largo del mundo desde tiempos antiguos, la cual se ha caracterizado por su gran variedad y diversidad al momento de crearla y expresarla. También, la música dentro de una sociedad no es algo estático, es decir, que permanece de una misma forma en el tiempo, sino que va evolucionando con el paso de los años en conjunto con las características de la época, las modas y gustos que se van instaurando en la sociedad. 

\ \ \ \ En relación con lo anterior, se podría decir que la existencia de los rankings musicales son un gran aporte al momento de dar cuenta de las tendencias musicales (relacionado tanto al género de música como al artista) más populares en un contexto o tiempo determinado. De esta manera, al estudiar y analizar ranking musicales en solitario o en conjunto, se puede ir observando la forma en que van cambiando los gustos de las personas, las tendencias musicales y los artistas y/o bandas más populares a lo largo del tiempo.

\ \ \ \ En este informe se intentará comprender esta misma evolución de los gustos y estilos musicales en los Estados Unidos entre los años 1960 y 2010, a través del ranking "Billboard Hot 100", el cual se constituye de una lista semanal de las canciones más populares dentro del país (agregar fuente). 

\ \ \ \ Para tal motivo, se necesitará explicar en qué cómo funciona el ranking mencionado anteriormente, cómo se relaciona el artista y género de música con el año o período analizado...(profe aún estoy media perdida en qué escribir en este párrafo la verdad, así que lo dejaré así por mientras :( )